version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}  # Pass env from .env
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
